// © Copyright 20/01/2023 Daniel Kenneth Bullimore
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
//@version=6

indicator("Vortex Magnitude")
ProfitShort = input.float(title="Mag One", defval=1.2, minval=0, maxval=100)
ProfitMid   = input.float(title="Mag Ten", defval=3, minval=0, maxval=100)
ProfitLong  = input.float(title="Mag Hundred", defval=36, minval=0, maxval=10000)

threeHundy = ta.sma(close, 300)
sixHundy = ta.sma(close,600)
nineHundy = ta.sma(close, 900)
ninetyspan =  (  (sixHundy - nineHundy)  /  (threeHundy-nineHundy)  *  100   )//what percent of wave height is 6
//plot(ninetyspan)

InVortex =  ninetyspan > ProfitLong - ProfitShort and ninetyspan < ProfitLong + ProfitShort 
OutVortex = ninetyspan < (100 - (ProfitLong - ProfitShort)) and ninetyspan > (100 - (ProfitLong + ProfitShort))


ninetybull = (InVortex and close > sixHundy and threeHundy > sixHundy and sixHundy > nineHundy) //ninetyspan > 75 and sixtynine < 63 and
ninetybear = (OutVortex and close < nineHundy and close < open)

ninetycolor= if (ninetybull)
    color.new(#00ff00 , 60)
else if (ninetybear)
    color.new(#ff0000,60) 
else 
    color.new(#000000, 75)
plot (27,  title='nintyOn', style=plot.style_circles,  color=ninetycolor, linewidth=20)//plot (sma(close,90),







//plot(sma((close),60), title='ST3', style=(0), color=color.purple, transp=0,  linewidth=2)
sixtyspan = ta.sma(close,60) / ta.sma(close, 90) * 100
sixtybull = (sixtyspan > (100+ProfitMid) and close > ta.sma(close, 30) and ta.sma(close, 30) > ta.sma(close,60) and ta.sma(close,60) > ta.sma(close, 90) ) //102
sixtybear = (sixtyspan < (100-ProfitMid) and close < ta.sma(close, 30) and ta.sma(close, 30) < ta.sma(close,60) and ta.sma(close, 60) < ta.sma(close, 90) ) //98
sixtycolor = if (sixtybull)
    color.new(#00ff00, 60)
else if (sixtybear)
    color.new(#ff0000,60) 
else 
    color.new(color.white, 100)
plot(27,  title='sixtyOn', style=plot.style_circles,  color=sixtycolor,  linewidth=10)  //plot(sma(close,60),






//plot(sma((close),30), title='ST1', style=(0), color=color.blue, transp=0 , linewidth=2)
thirtyspan = ta.sma(close,3) / ta.sma(close,6) * 100
thirtybull = (thirtyspan >= (100 + ProfitShort) and close >= ta.sma(close, 3) and ta.sma(close, 3) > ta.sma(close,6) and ta.sma(close,6) > ta.sma(close, 9) ) //102
thirtybear = (thirtyspan <= (100 - ProfitShort) and close <= ta.sma(close, 3) and ta.sma(close, 3) < ta.sma(close,6) and  ta.sma(close,6) < ta.sma(close, 9) )   //96
thirtycolor = if  (thirtybull)
    color.new(#00ff00, 0)
else if (thirtybear)
    color.new(#ff0000, 0)
else 
    color.new(#FF6600, 0)  
plot(27,  title='thirtyOn', style=plot.style_circles,  color=thirtycolor,  linewidth=3)//plot(sma(close,30),

ninevolume = ((ta.sma(volume,9) / volume * 100 ) < 35)





